name: Workflow PR

on:
    pull_request:
        branches: 
            - workspace_diego
        types: [opened, reopened, synchronize]
    push: 
        branches:
            -develop

jobs:
    test-build:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set Go version
          uses: actions/setup-go@v5
          with:
             go-version: '1.21'

        - name: Build
          run: go build -o main

        - name: Run Go Server
          run: nohup ./main &

        - name: Wait for server to start
          run: sleep 5

        - name: Verify server is running 
          run: |
             RESPONSE=$(curl http://localhost:8080/status)
             if echo "$RESPONSE" | grep -q '"status":"OK"'; then
                 echo "server is running and returned OK"
             else
                 echo "Server did not return expected ID."
                 exit 1
             fi

